repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml

# zizmor detects security vulnerabilities in GitHub Actions workflows.
- repo: https://github.com/woodruffw/zizmor-pre-commit
  rev: v1.4.1
  hooks:
    - id: zizmor

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.31.2
  hooks:
    - id: check-github-workflows
      args: ["--verbose"]
    - id: check-compose-spec
      args: ["--verbose"]
    - id: check-renovate
      args: ["--verbose"]
      additional_dependencies: ['json5']

# `actionlint` hook, for verifying correct syntax in GitHub Actions workflows.
# Some additional configuration for `actionlint` can be found in `.github/actionlint.yaml`.
- repo: https://github.com/rhysd/actionlint
  rev: v1.7.7
  hooks:
    - id: actionlint
      language: golang
      additional_dependencies:
        # actionlint has a shellcheck integration which extracts shell scripts in `run:` steps from GitHub Actions
        # and checks these with shellcheck. This is arguably its most useful feature,
        # but the integration only works if shellcheck is installed
        - "github.com/wasilibs/go-shellcheck/cmd/shellcheck@v0.10.0"
