name: pre-commit
description: run pre-commit
inputs:
  extra_args:
    description: options to pass to pre-commit run
    required: false
    default: '--all-files'
runs:
  using: composite
  steps:
  - run: echo "pythonVersion=$(python -c 'import platform; print(platform.python_version());')" >> "$GITHUB_ENV" # zizmor: ignore[github-env]
    shell: bash
  - uses: actions/cache@v4
    with:
      path: ~/.cache/pre-commit
      key: pre-commit-3|${{ env.pythonVersion }}|${{ hashFiles('.pre-commit-config.yaml') }}
  - run: |
      UV_PREFIX=
      if command -v uv; then
        echo "uv is installed"
        # attempt to activate virtual environment if it exists
        source .venv/bin/activate || true
        if command -v uv.lock; then
          echo "using uv run"
          UV_PREFIX="uv run --no-sync"
        else
          echo "using uvx"
          UV_PREFIX="uvx"
        fi
      else
        echo "uv not installed, using pip"
        pip install pre-commit
      fi
      echo "Running pre-commit with: ${UV_PREFIX} pre-commit"
      $UV_PREFIX pre-commit run --show-diff-on-failure --color=always $EXTRA_ARGS
    shell: bash
    env:
      EXTRA_ARGS: ${{ inputs.extra_args }}
